package puzzle2;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author abdul karim
 */
public class timeoff extends javax.swing.JFrame {

    /**
     * Creates new form timeoff
     */
    public timeoff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num6 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnreset = new javax.swing.JButton();
        btnundo = new javax.swing.JButton();
        Display1 = new javax.swing.JTextField();
        Display2 = new javax.swing.JTextField();
        Display3 = new javax.swing.JTextField();
        Display4 = new javax.swing.JTextField();
        Display5 = new javax.swing.JTextField();
        Display6 = new javax.swing.JTextField();
        Display7 = new javax.swing.JTextField();
        Display8 = new javax.swing.JTextField();
        Display9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        TimerTx = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        btnexit = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        pos9 = new javax.swing.JButton();
        pos6 = new javax.swing.JButton();
        pos3 = new javax.swing.JButton();
        pos2 = new javax.swing.JButton();
        pos5 = new javax.swing.JButton();
        pos8 = new javax.swing.JButton();
        pos7 = new javax.swing.JButton();
        pos4 = new javax.swing.JButton();
        pos1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle");
        setBounds(new java.awt.Rectangle(200, 70, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(366, 490));
        setMinimumSize(new java.awt.Dimension(366, 490));
        setPreferredSize(new java.awt.Dimension(366, 490));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 240, 70, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Position");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 240, 70, 30);

        num6.setBackground(new java.awt.Color(0, 51, 51));
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6);
        num6.setBounds(300, 330, 40, 25);

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9);
        num9.setBounds(300, 370, 40, 25);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 153, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(51, 51, 0), new java.awt.Color(51, 51, 0))));
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 500));
        jPanel1.setLayout(null);

        btnreset.setBackground(new java.awt.Color(8, 5, 79));
        btnreset.setForeground(new java.awt.Color(204, 5, 5));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset);
        btnreset.setBounds(260, 200, 70, 25);

        btnundo.setBackground(new java.awt.Color(188, 101, 19));
        btnundo.setText("Undo");
        btnundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnundoActionPerformed(evt);
            }
        });
        jPanel1.add(btnundo);
        btnundo.setBounds(20, 200, 59, 25);

        Display1.setEditable(false);
        Display1.setBackground(new java.awt.Color(74, 112, 77));
        Display1.setForeground(new java.awt.Color(0, 0, 0));
        Display1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display1.setRequestFocusEnabled(false);
        Display1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display1);
        Display1.setBounds(40, 50, 80, 29);

        Display2.setEditable(false);
        Display2.setBackground(new java.awt.Color(74, 112, 77));
        Display2.setForeground(new java.awt.Color(0, 0, 0));
        Display2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display2.setRequestFocusEnabled(false);
        Display2.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display2);
        Display2.setBounds(140, 50, 80, 29);

        Display3.setEditable(false);
        Display3.setBackground(new java.awt.Color(74, 112, 77));
        Display3.setForeground(new java.awt.Color(0, 0, 0));
        Display3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display3.setRequestFocusEnabled(false);
        Display3.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display3);
        Display3.setBounds(250, 50, 80, 29);

        Display4.setEditable(false);
        Display4.setBackground(new java.awt.Color(74, 112, 77));
        Display4.setForeground(new java.awt.Color(0, 0, 0));
        Display4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display4.setRequestFocusEnabled(false);
        Display4.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display4);
        Display4.setBounds(40, 90, 80, 29);

        Display5.setEditable(false);
        Display5.setBackground(new java.awt.Color(74, 112, 77));
        Display5.setForeground(new java.awt.Color(0, 0, 0));
        Display5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display5.setRequestFocusEnabled(false);
        Display5.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display5);
        Display5.setBounds(140, 90, 80, 29);

        Display6.setEditable(false);
        Display6.setBackground(new java.awt.Color(74, 112, 77));
        Display6.setForeground(new java.awt.Color(0, 0, 0));
        Display6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display6.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display6.setRequestFocusEnabled(false);
        Display6.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display6);
        Display6.setBounds(250, 90, 80, 29);

        Display7.setEditable(false);
        Display7.setBackground(new java.awt.Color(74, 112, 77));
        Display7.setForeground(new java.awt.Color(0, 0, 0));
        Display7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display7.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display7.setRequestFocusEnabled(false);
        Display7.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display7);
        Display7.setBounds(40, 130, 80, 29);

        Display8.setEditable(false);
        Display8.setBackground(new java.awt.Color(74, 112, 77));
        Display8.setForeground(new java.awt.Color(0, 0, 0));
        Display8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display8.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display8.setRequestFocusEnabled(false);
        Display8.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display8);
        Display8.setBounds(140, 130, 80, 29);

        Display9.setEditable(false);
        Display9.setBackground(new java.awt.Color(74, 112, 77));
        Display9.setForeground(new java.awt.Color(0, 0, 0));
        Display9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display9.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102))));
        Display9.setRequestFocusEnabled(false);
        Display9.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(Display9);
        Display9.setBounds(250, 130, 80, 29);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 255), new java.awt.Color(153, 153, 255)), new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 3, true)));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 30, 340, 160);

        TimerTx.setEditable(false);
        TimerTx.setBackground(new java.awt.Color(153, 153, 153));
        TimerTx.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TimerTx.setForeground(new java.awt.Color(255, 0, 0));
        TimerTx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TimerTx.setText(" Null");
        TimerTx.setToolTipText("");
        TimerTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimerTxActionPerformed(evt);
            }
        });
        jPanel1.add(TimerTx);
        TimerTx.setBounds(190, 10, 70, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setForeground(new java.awt.Color(0, 255, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Time:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 10, 80, 19);

        btnexit.setBackground(new java.awt.Color(153, 153, 153));
        btnexit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(153, 0, 51));
        btnexit.setText("X");
        btnexit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(51, 204, 255)));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit);
        btnexit.setBounds(300, 5, 50, 28);

        num2.setBackground(new java.awt.Color(0, 51, 51));
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2);
        num2.setBounds(250, 290, 40, 25);

        num5.setBackground(new java.awt.Color(204, 204, 255));
        num5.setForeground(new java.awt.Color(0, 0, 255));
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel1.add(num5);
        num5.setBounds(250, 330, 40, 25);

        num8.setBackground(new java.awt.Color(0, 51, 51));
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel1.add(num8);
        num8.setBounds(250, 370, 40, 25);

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel1.add(num1);
        num1.setBounds(190, 290, 40, 25);

        num4.setBackground(new java.awt.Color(0, 51, 51));
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel1.add(num4);
        num4.setBounds(190, 330, 40, 25);

        num7.setBackground(new java.awt.Color(204, 204, 255));
        num7.setForeground(new java.awt.Color(0, 0, 255));
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        jPanel1.add(num7);
        num7.setBounds(190, 370, 40, 25);

        num3.setBackground(new java.awt.Color(204, 204, 255));
        num3.setForeground(new java.awt.Color(0, 0, 255));
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel1.add(num3);
        num3.setBounds(300, 290, 40, 25);

        pos9.setBackground(new java.awt.Color(204, 204, 255));
        pos9.setForeground(new java.awt.Color(255, 51, 51));
        pos9.setText("9");
        pos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos9ActionPerformed(evt);
            }
        });
        jPanel1.add(pos9);
        pos9.setBounds(120, 370, 40, 25);

        pos6.setText("6");
        pos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos6ActionPerformed(evt);
            }
        });
        jPanel1.add(pos6);
        pos6.setBounds(120, 330, 40, 25);

        pos3.setBackground(new java.awt.Color(51, 153, 0));
        pos3.setText("3");
        pos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos3ActionPerformed(evt);
            }
        });
        jPanel1.add(pos3);
        pos3.setBounds(120, 290, 40, 25);

        pos2.setText("2");
        pos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos2ActionPerformed(evt);
            }
        });
        jPanel1.add(pos2);
        pos2.setBounds(70, 290, 40, 25);

        pos5.setBackground(new java.awt.Color(204, 204, 255));
        pos5.setForeground(new java.awt.Color(255, 51, 51));
        pos5.setText("5");
        pos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos5ActionPerformed(evt);
            }
        });
        jPanel1.add(pos5);
        pos5.setBounds(70, 330, 40, 25);

        pos8.setText("8");
        pos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos8ActionPerformed(evt);
            }
        });
        jPanel1.add(pos8);
        pos8.setBounds(70, 370, 40, 25);

        pos7.setBackground(new java.awt.Color(51, 153, 0));
        pos7.setText("7");
        pos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos7ActionPerformed(evt);
            }
        });
        jPanel1.add(pos7);
        pos7.setBounds(20, 370, 40, 25);

        pos4.setText("4");
        pos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos4ActionPerformed(evt);
            }
        });
        jPanel1.add(pos4);
        pos4.setBounds(20, 330, 40, 25);

        pos1.setBackground(new java.awt.Color(204, 204, 255));
        pos1.setForeground(new java.awt.Color(255, 51, 51));
        pos1.setText("1");
        pos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos1ActionPerformed(evt);
            }
        });
        jPanel1.add(pos1);
        pos1.setBounds(20, 290, 40, 25);

        jPanel3.setBackground(new java.awt.Color(50, 30, 25));
        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 280, 160, 140);

        jPanel4.setBackground(new java.awt.Color(50, 47, 2));
        jPanel1.add(jPanel4);
        jPanel4.setBounds(180, 280, 170, 140);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(204, 255, 204)));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 102, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 0, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Game");
        jTextField2.setBorder(null);
        jPanel5.add(jTextField2);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 430, 360, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 460);
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }
                            
                         
     private void num1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f1==0){
            s="1";
            Puzzle2.numssound();
        }
        
    }                                    

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f2==0){
            s="2";
            Puzzle2.numssound();
        } 

    }                                    

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f3==0){
            Puzzle2.numssound();
            s="3";
        }  
    }                                    

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f4==0){
            Puzzle2.numssound();
            s="4";
        }  
    }                                    

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f5==0){
            Puzzle2.numssound();
            s="5";
        }  
    }                                    

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f6==0){
            Puzzle2.numssound();
            s="6";
        }  
    }                                    

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f7==0){
            Puzzle2.numssound();
            s="7";
        }  
    }                                    

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f8==0){
            Puzzle2.numssound();
            s="8";
        }
    }                                    

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(f9==0){
            Puzzle2.numssound();
            s="9";
        } 
    }                                    

    private void pos1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(Display1.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=1;
                Display1.setText(s);
                Puzzle2.possound();
            }
            number(1);    
        }
                
                check();
                s=new String();
    }                                    
        
    private void pos2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(Display2.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=2;
                Display2.setText(s);
                Puzzle2.possound();
            }
               number(2); 
            }
                
                check();
                s=new String();
    }                                    

    private void pos3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(Display3.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=3;
                Display3.setText(s);
                Puzzle2.possound();
            }
             number(3);   
         }
                
                check();
                s=new String();
    }                                    

    private void pos4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(Display4.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=4;//undo check 
                Display4.setText(s);
                Puzzle2.possound();
            }
             number(4);   
        }
                
                check();
                s=new String();
    }                                    

    private void pos5ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        if(Display5.getText().isEmpty())
            {
                if(s.length()>0){
                index++;
                array[index]=5;//undo check 
                Display5.setText(s);
                Puzzle2.possound();
                }
                number(5);
            }
                
                check();
                s=new String();
    }                                    

    private void pos6ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        if(Display6.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=6;//undo check 
                Display6.setText(s);
                Puzzle2.possound();
            }
             number(6);   
        }
            
            check();
            s=new String();
    }                                    

    private void pos7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        if(Display7.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=7;//undo check array
                Display7.setText(s);
                Puzzle2.possound();
            }
            number(7);    
        }
        
        check();
        s=new String();
    }                                    

    private void pos8ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        if(Display8.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=8;//undo check array
                Display8.setText(s);
                Puzzle2.possound();
            }
             number(8);   
        }
        
        check();
        s=new String();

    }                                    

    private void pos9ActionPerformed(java.awt.event.ActionEvent evt) {                                     

        if(Display9.getText().isEmpty())
        {
            if(s.length()>0){
                index++;
                array[index]=9;//undo check array
                Display9.setText(s);
                Puzzle2.possound();
            }
             number(9);
            } 
        check();
      s=new String();

    }                                    

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        reset();
        Puzzle2.numssound();
    }                                        

    private void btnundoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if(index !=-1 || ind !=-1){
        undo();
        Puzzle2.numssound();
        }else
            Puzzle2.errorsound();
    }                                                                              

    private void TimerTxActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Puzzle2.numssound();
        System.exit(0);
    }                                       
    
    String s=new String();
    void check()
    {
       if(!Display1.getText().isEmpty())
       flag1=Integer.parseInt(Display1.getText());
       if(!Display2.getText().isEmpty())
       flag2=Integer.parseInt(Display2.getText());
       if(!Display3.getText().isEmpty())
       flag3=Integer.parseInt(Display3.getText());
       if(!Display4.getText().isEmpty())
       flag4=Integer.parseInt(Display4.getText());
       if(!Display5.getText().isEmpty())
       flag5=Integer.parseInt(Display5.getText());
       if(!Display6.getText().isEmpty())
       flag6=Integer.parseInt(Display6.getText());
       if(!Display7.getText().isEmpty())
       flag7=Integer.parseInt(Display7.getText());
       if(!Display8.getText().isEmpty())
       flag8=Integer.parseInt(Display8.getText());
       if(!Display9.getText().isEmpty())
       flag9=Integer.parseInt(Display9.getText());
    /*** winning condition check() ***/
    // we are looking for 8 conditions
       if(flag1+flag2+flag3==15 && flag4+flag5+flag6==15 && flag7+flag8+flag9==15 && flag1+flag4+flag7==15 && flag2+flag5+flag8==15 && flag3+flag6+flag9==15 && flag1+flag5+flag9==15 && flag3+flag5+flag7==15)
       {
           new Frame2().setVisible(true);
           this.setVisible(false);
           try {
                    Music.winsound();
           }catch (Exception ex) {
                    Logger.getLogger(Puzzle2.class.getName()).log(Level.SEVERE, null, ex);
                }
       }
       if((flag1+flag2+flag3!=15 || flag4+flag5+flag6!=15 || flag7+flag8+flag9!=15 || flag1+flag4+flag7!=15 || flag2+flag5+flag8!=15 || flag3+flag6+flag9!=15 || flag1+flag5+flag9!=15 || flag3+flag5+flag7!=15)&&(flag1 !=0 && flag2 !=0 && flag3 !=0 && flag4 !=0 && flag5 !=0 && flag6 !=0 && flag7 !=0 && flag8 !=0 && flag9 !=0)){

           new Frame1().setVisible(true);
           this.setVisible(false);
           try {
                    Music.losssound();
           }catch (Exception ex) {
                    Logger.getLogger(Puzzle2.class.getName()).log(Level.SEVERE, null, ex);
                }

       }

    }
    void reset(){
        //if(r !=0){
            flag1=0;flag2=0;flag3=0;flag4=0;flag5=0;flag6=0;flag7=0;flag8=0;flag9=0;
            f=0;f1=0;f2=0;f3=0;f4=0;f5=0;f6=0;f7=0;f8=0;f9=0;
            index=-1;ind=-1;
            TimerTx.setText("Null");
            s=new String();
            num1.setEnabled(true);
            num2.setEnabled(true);
            num3.setEnabled(true);
            num4.setEnabled(true);
            num5.setEnabled(true);
            num6.setEnabled(true);
            num7.setEnabled(true);
            num8.setEnabled(true);
            num9.setEnabled(true);
            Display1.setText(s);
            Display2.setText(s);
            Display3.setText(s);
            Display4.setText(s);
            Display5.setText(s);
            Display6.setText(s);
            Display7.setText(s);
            Display8.setText(s);
            Display9.setText(s);
            
        //}
    }
    void undo(){
        int pos,num;
        s=new String();
        if(ind != -1){
            num=array2[ind];
            if(num==1){
                f1=0;
            }else if(num==2){
                f2=0;
            }else if(num==3){
                f3=0;
            }else if(num==4){
                f4=0;
            }else if(num==5){
                f5=0;
            }else if(num==6){
                f6=0;
            }else if(num==7){
                f7=0;
            }else if(num==8){
                f8=0;
            }else if(num==9){
                f9=0;
            }
            ind--;
        }
        if(index !=-1){
            
            pos=array[index];
            switch (pos) {
                case 1:
                    Display1.setText(s);
                    flag1=0;
                    break;
                case 2:
                    Display2.setText(s);
                    flag2=0;
                    break;
                case 3:
                    Display3.setText(s);
                    flag3=0;
                    break;
                case 4:
                    Display4.setText(s);
                    flag4=0;
                    break;
                case 5:
                    Display5.setText(s);
                    flag5=0;
                    break;
                case 6:
                    Display6.setText(s);
                    flag6=0;
                    break;
                case 7:
                    Display7.setText(s);
                    flag7=0;
                    break;
                case 8:
                    Display8.setText(s);
                    flag8=0;
                    break;
                case 9:
                    Display9.setText(s);
                    flag9=0;
                    break;
                default:
                    break;
            }
            
            index--;
        }
        
        
    }
    public void number(int a){

        if(a==1){
            if(Display1.getText().length()>0){

                f=Integer.parseInt(Display1.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }
            }
        }else if(a==2){
            if(Display2.getText().length()>0){
                f=Integer.parseInt(Display2.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }
  
            }
        }else if(a==3){
            if(Display3.getText().length()>0){
                f=Integer.parseInt(Display3.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }  
            }
        }else if(a==4){
            if(Display4.getText().length()>0){
                f=Integer.parseInt(Display4.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }  
            }
        }else if(a==5){
            if(Display5.getText().length()>0){
                f=Integer.parseInt(Display5.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                } 
            }
        }else if(a==6){
            if(Display6.getText().length()>0){
                f=Integer.parseInt(Display6.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }   
            }
        }else if(a==7){
            if(Display7.getText().length()>0){
                f=Integer.parseInt(Display7.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }  
            }
        }else if(a==8){
            if(Display8.getText().length()>0){
                f=Integer.parseInt(Display8.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }  
            }
        }else if(a==9){
            if(Display9.getText().length()>0){
                f=Integer.parseInt(Display9.getText());
                ind++;
                array2[ind]=f;
                if(f==1){
                    f1=1;
                    num1.setEnabled(false);
                }else if(f==2){
                    f2=1;
                    num2.setEnabled(false);
                }else if(f==3){
                    f3=1;
                    num3.setEnabled(false);
                }else if(f==4){
                    f4=1;
                    num4.setEnabled(false);
                }else if(f==5){
                    f5=1;
                    num5.setEnabled(false);
                }else if(f==6){
                    f6=1;
                    num6.setEnabled(false);
                }else if(f==7){
                    f7=1;
                    num7.setEnabled(false);
                }else if(f==8){
                    f8=1;
                    num8.setEnabled(false);
                }else if(f==9){
                    f9=1;
                    num9.setEnabled(false);
                }
            }
        }
    }
    void Time(){
        JOptionPane.showMessageDialog(this,"Time Over\nPress ok to Try Again");
    }
    public int index=-1,ind=-1;//index text field position decle and ind numbe  enable checker
    public int array[]= new int[9];//text field enable check array
    public int array2[]= new int[9];//number Enable check array
    public int f=0,f1=0,f2=0,f3=0,f4=0,f5=0,f6=0,f7=0,f8=0,f9=0;//number Enable check variable
    int flag1=0,flag2=0,flag3=0,flag4=0,flag5=0,flag6=0,flag7=0,flag8=0,flag9=0;//win or loss conditon check variable

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timeoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timeoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timeoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timeoff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new timeoff().setVisible(true);
            }
        });
    }
    private javax.swing.JTextField Display1;
    private javax.swing.JTextField Display2;
    private javax.swing.JTextField Display3;
    private javax.swing.JTextField Display4;
    private javax.swing.JTextField Display5;
    private javax.swing.JTextField Display6;
    private javax.swing.JTextField Display7;
    private javax.swing.JTextField Display8;
    private javax.swing.JTextField Display9;
    private javax.swing.JTextField TimerTx;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton pos1;
    private javax.swing.JButton pos2;
    private javax.swing.JButton pos3;
    private javax.swing.JButton pos4;
    private javax.swing.JButton pos5;
    private javax.swing.JButton pos6;
    private javax.swing.JButton pos7;
    private javax.swing.JButton pos8;
    private javax.swing.JButton pos9;
    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
